### ISSUE TITLE
Extend/Switch ASCII to Unicode

### ISSUE THREAD

**Issue by KrishnadevL** [KrishnadevL/flask_portfolio#38]
Use representation of U-0000 to U-FFFF for your bits.  The extension of ASCII to Unicode mode allows you to show even more Characters and Character ranges.

**Comment by samayasankuratri** [comment]
[ASCII and Unicode Switch](https://github.com/KrishnadevL/flask_portfolio/blob/6253162ea6020a1568a90c8f7b6c711535959281/templates/Binary.html#L118-L126)
If statement used where if the decimal value was greater than 127 the character would be displayed in the Unicode part of the table else the character would be displayed in the ASCII part.
