### ISSUE TITLE
Unsigned Addition

### ISSUE THREAD

**Issue by KrishnadevL** [KrishnadevL/flask_portfolio#40]
Subtraction (Default).  Whole Numbers. Max number move from 255 to 65535.  Essentially 8 bits to 16 bits.  16 bits is often called a "Short Integer".

**Comment by samayasankuratri** [comment]
[Function Unsigned Addition](https://github.com/KrishnadevL/flask_portfolio/blob/6253162ea6020a1568a90c8f7b6c711535959281/templates/Binary_math.html#L188-L201)
Converted binary from both inputs to decimal, and added them together, and set to variable to be displayed.
